/* From ABNB.sas: initial exploration of the stock-price panel.
   WORK.STOCKS is loaded by autoexec.sas from the bundled sample. */

PROC CONTENTS DATA=WORK.STOCKS; RUN;

proc univariate data=stocks;
   *var ABNB;
   histogram ABNB AMZN APTV AZO BBWI BBY BKNG BWA CCL CMG CZR DECK DHI DPZ DRI EBAY ETSY EXPE F GM GPC GRMN HAS HD HLT KMX LEN LKQ LOW LULU LVS MAR MCD MGM MHK NCLH NKE NVR ORLY PHM POOL RCL RL ROST SBUX TJX TPR TSCO TSLA ULTA WYNN YUM;
   inset N MEAN STD / position=ne;
run;

proc means data= stocks;
	var ABNB AMZN APTV AZO BBWI BBY BKNG BWA CCL CMG CZR DECK DHI DPZ DRI EBAY ETSY EXPE F GM GPC GRMN HAS HD HLT KMX LEN LKQ LOW LULU LVS MAR MCD MGM MHK NCLH NKE NVR ORLY PHM POOL RCL RL ROST SBUX TJX TPR TSCO TSLA ULTA WYNN YUM;;
	run;
